name: Check Perl Scripts
on: push

jobs:
  build:
    name: Check greeting.pl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: perl -v
      - run: uname -a
      - run: perl -wc greeting.pl
